"""image_ratings

Revision ID: b18b0733f2df
Revises: 197fda1bbd91
Create Date: 2024-05-08 23:08:49.449260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18b0733f2df'
down_revision: Union[str, None] = '197fda1bbd91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_black_list_email'), 'black_list', ['email'], unique=True)
    op.create_index(op.f('ix_black_list_id'), 'black_list', ['id'], unique=False)
    op.create_index(op.f('ix_black_list_token'), 'black_list', ['token'], unique=True)
    op.create_table('image_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_ratings_id'), 'image_ratings', ['id'], unique=False)
    op.add_column('images', sa.Column('average_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'average_rating')
    op.drop_index(op.f('ix_image_ratings_id'), table_name='image_ratings')
    op.drop_table('image_ratings')
    op.drop_index(op.f('ix_black_list_token'), table_name='black_list')
    op.drop_index(op.f('ix_black_list_id'), table_name='black_list')
    op.drop_index(op.f('ix_black_list_email'), table_name='black_list')
    op.drop_table('black_list')
    # ### end Alembic commands ###
